platform :ios, '9.3'

use_frameworks!

target 'Rules_Example' do
  pod 'Rules', :path => '../'

  target 'Rules_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
