platform :ios, '9.0'

use_frameworks!

target 'Rules_Example' do
  pod 'Rules', :path => '../'

  target 'Rules_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3', :inhibit_warnings => true
    pod 'Nimble', '~> 7.1', :inhibit_warnings => true
  end
end
